CREATE DATABASE DBMS;
USE DBMS;

CREATE TABLE customer(
    customer_id INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    MOBILE VARCHAR(50),
    YOUR_TYPE VARCHAR(50),
    AMOUNT VARCHAR(50),
    EMAIL VARCHAR(50)
);